const pattern = {
  DATE_FORMAT: 'DD-MM-YYYY',
  YEAR_MONTH_DATE: 'YYYY-MM-DD',
  YEAR_MONTH_DATE_WITH_TIME: 'YYYY-MM-DD h:mm A',
  DATE_LABEL_FORMAT: 'Do MMM',
  DATE_SUB_FORMAT: 'DD MMM YYYY',
  MONTH_YEAR_FORMAT: 'MMM YYYY',
  SMALL_MONTH_YEAR: 'MM YYYY',
  FULL_MONTH_YEAR_FORMAT: 'MMMM YYYY',
};

export default pattern;
